<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE registro_usuario [
<!ELEMENT registro_usuario (usuario_unico)*>
<!ELEMENT usuario_unico (usuario , contrasena , nombreCompleto , direccion , celular)>
<!ELEMENT usuario (#PCDATA)>
<!ELEMENT contrasena (#PCDATA)>
<!ELEMENT nombreCompleto (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT celular (#PCDATA)>
]>
<registro_usuario>
	
<usuario_unico>
	<usuario>cristhian</usuario>
	<contrasena>123</contrasena>
	<nombreCompleto>cristhian david</nombreCompleto>
	<direccion>no s√© </direccion>
	<celular>22323</celular>
</usuario_unico>
<usuario_unico>
	<usuario>david</usuario>
	<contrasena>123456</contrasena>
	<nombreCompleto>david hoyos t</nombreCompleto>
	<direccion>cra 9 a </direccion>
	<celular>3242</celular>
</usuario_unico>
<usuario_unico>
	<usuario>cristhian</usuario>
	<contrasena>cristhian12331</contrasena>
	<nombreCompleto>231</nombreCompleto>
	<direccion>sad</direccion>
	<celular>231</celular>
</usuario_unico>
<usuario_unico>
	<usuario>tester</usuario>
	<contrasena>testerqa</contrasena>
	<nombreCompleto>soy un tester :D</nombreCompleto>
	<direccion>no me acuerdo</direccion>
	<celular>32</celular>
</usuario_unico>
<usuario_unico>
	<usuario>Angie2902</usuario>
	<contrasena>Angie12</contrasena>
	<nombreCompleto>Angie Florez</nombreCompleto>
	<direccion>39</direccion>
	<celular>321382763</celular>
</usuario_unico>
	
</registro_usuario>
